# Generated by Django 3.2.13 on 2022-07-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('journal_title', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('discipline', models.CharField(choices=[('1. natural sciences', 'Natsci'), ('1.1. mathematics', 'Math'), ('1.2. computer and information sciences', 'It'), ('1.3. physical sciences', 'Pe'), ('1.4. chemical sciences', 'Chem'), ('1.5. earth and related environmental sciences', 'Earth'), ('1.6. biological sciences', 'Bio'), ('1.7. other natural sciences', 'Othernat'), ('2. engineering and technology', 'Engtech'), ('2.1. civil engineering', 'Civeng'), ('2.2. electrical engineering, electronic engineering, information engineering', 'Eleceng'), ('2.3. mechanical engineering', 'Mecheng'), ('2.4. chemical engineering', 'Chemeng'), ('2.5. materials engineering', 'Mateng'), ('2.6. medical engineering', 'Medeng'), ('2.7. environmental engineering', 'Enveng'), ('2.8. environmental biotechnology', 'Envbio'), ('2.9. industrial biotechnology', 'Indeng'), ('2.10. nano-technology', 'Nanotech'), ('2.11. other engineering and technologies', 'Othereng'), ('3. medical and health sciences', 'Medhealth'), ('3.1. basic medicine', 'Basicmed'), ('3.2. clinical medicine', 'Clinicmed'), ('3.3. health sciences', 'Healthsci'), ('3.4. medical biotechnology', 'Medibio'), ('3.5. other medical sciences', 'Othermed'), ('4. agricultural and veterinary sciences', 'Agrivet'), ('4.1. agriculture, forestry and fisheries', 'Agriforest'), ('4.2. animal and dairy science', 'Animaldairy'), ('4.3. veterinary science', 'Vetsci'), ('4.4. agricultural biotechnology', 'Agribio'), ('4.5. other agricultural sciences', 'Otheragri'), ('5. social sciences', 'Socialsci'), ('5.1. psychology and cognitive sciences', 'Psycho'), ('5.2. economics and business', 'Economics'), ('5.3. educational sciences', 'Edu'), ('5.4. sociology', 'Sociology'), ('5.5. law', 'Law'), ('5.6. political science', 'Polsci'), ('5.7. social and economic geography', 'Socgeo'), ('5.8. media and communications', 'Medcom'), ('5.9. other social sciences', 'Othersoc'), ('6. humanities', 'Human'), ('6.1. history and archaeology', 'Hist'), ('6.2. languages and literature', 'Lang'), ('6.3. philosophy, ethics and religion', 'Phil'), ('6.4. arts (arts, history of arts, performing arts, music)', 'Arts'), ('6.5. other humanities', 'Otherhum'), ('all disciplines', 'All'), ('all stem disciplines', 'Allstem'), ('all hss disciplines', 'Allhss')], max_length=80)),
                ('owner_ror_id', models.CharField(max_length=100, null=True)),
                ('publisher_ror_id', models.CharField(max_length=100, null=True)),
                ('apc_list_price_range_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apc_list_price_range_higher', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apc_list_price_currency', models.CharField(max_length=3)),
                ('apc_waiver_discount_policy', models.URLField(null=True)),
                ('subscription_list_price_range_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_range_higher', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_for_member_of_the_association_of_americ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_currency', models.CharField(max_length=3)),
                ('subscription_discount_policy', models.URLField(null=True)),
                ('rejection_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discounts_and_waivers_policy', models.URLField(null=True)),
                ('notes', models.TextField(null=True)),
                ('price_transparency_context', models.URLField(null=True)),
                ('research_articles_published', models.IntegerField()),
                ('acceptance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issue_publication_frequency', models.CharField(choices=[('annual', 'Annual'), ('bimonthly', 'Bimonthly'), ('semiweekly', 'Semiweekly'), ('daily', 'Daily'), ('biweekly', 'Biweekly'), ('semiannual', 'Semiannual'), ('biennial', 'Biennial'), ('triennial', 'Triennial'), ('three times a week', 'Three A Week'), ('three times a month', 'Three A Month'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semimonthly', 'Semimonthly'), ('three times a year', 'Three A Year'), ('weekly', 'Weekly'), ('continuously updated', 'Cont'), ('other', 'Other')], max_length=20)),
                ('median_number_reviews', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_time_submission_to_first_decision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_time_peer_review', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_time_acceptance_to_publication', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter_5_unique_item_requests', models.IntegerField(null=True)),
                ('counter_5_total_item_requests', models.IntegerField()),
                ('price_breakdown_journal_community_development', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_journal_submission_on_first_decision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_peer_review', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_services_acceptance_publication', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_services_post_publication', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_platform_development_support', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_sales_marketing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_author_customer_support', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FairOpenAccessAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('journal_title', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('discipline', models.CharField(choices=[('1. natural sciences', 'Natsci'), ('1.1. mathematics', 'Math'), ('1.2. computer and information sciences', 'It'), ('1.3. physical sciences', 'Pe'), ('1.4. chemical sciences', 'Chem'), ('1.5. earth and related environmental sciences', 'Earth'), ('1.6. biological sciences', 'Bio'), ('1.7. other natural sciences', 'Othernat'), ('2. engineering and technology', 'Engtech'), ('2.1. civil engineering', 'Civeng'), ('2.2. electrical engineering, electronic engineering, information engineering', 'Eleceng'), ('2.3. mechanical engineering', 'Mecheng'), ('2.4. chemical engineering', 'Chemeng'), ('2.5. materials engineering', 'Mateng'), ('2.6. medical engineering', 'Medeng'), ('2.7. environmental engineering', 'Enveng'), ('2.8. environmental biotechnology', 'Envbio'), ('2.9. industrial biotechnology', 'Indeng'), ('2.10. nano-technology', 'Nanotech'), ('2.11. other engineering and technologies', 'Othereng'), ('3. medical and health sciences', 'Medhealth'), ('3.1. basic medicine', 'Basicmed'), ('3.2. clinical medicine', 'Clinicmed'), ('3.3. health sciences', 'Healthsci'), ('3.4. medical biotechnology', 'Medibio'), ('3.5. other medical sciences', 'Othermed'), ('4. agricultural and veterinary sciences', 'Agrivet'), ('4.1. agriculture, forestry and fisheries', 'Agriforest'), ('4.2. animal and dairy science', 'Animaldairy'), ('4.3. veterinary science', 'Vetsci'), ('4.4. agricultural biotechnology', 'Agribio'), ('4.5. other agricultural sciences', 'Otheragri'), ('5. social sciences', 'Socialsci'), ('5.1. psychology and cognitive sciences', 'Psycho'), ('5.2. economics and business', 'Economics'), ('5.3. educational sciences', 'Edu'), ('5.4. sociology', 'Sociology'), ('5.5. law', 'Law'), ('5.6. political science', 'Polsci'), ('5.7. social and economic geography', 'Socgeo'), ('5.8. media and communications', 'Medcom'), ('5.9. other social sciences', 'Othersoc'), ('6. humanities', 'Human'), ('6.1. history and archaeology', 'Hist'), ('6.2. languages and literature', 'Lang'), ('6.3. philosophy, ethics and religion', 'Phil'), ('6.4. arts (arts, history of arts, performing arts, music)', 'Arts'), ('6.5. other humanities', 'Otherhum'), ('all disciplines', 'All'), ('all stem disciplines', 'Allstem'), ('all hss disciplines', 'Allhss')], max_length=80)),
                ('owner_ror_id', models.CharField(max_length=100, null=True)),
                ('publisher_ror_id', models.CharField(max_length=100, null=True)),
                ('apc_list_price_range_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apc_list_price_range_higher', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apc_list_price_currency', models.CharField(max_length=3)),
                ('apc_waiver_discount_policy', models.URLField(null=True)),
                ('subscription_list_price_range_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_range_higher', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_for_member_of_the_association_of_americ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_list_price_currency', models.CharField(max_length=3)),
                ('subscription_discount_policy', models.URLField(null=True)),
                ('rejection_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discounts_and_waivers_policy', models.URLField(null=True)),
                ('notes', models.TextField(null=True)),
                ('inhouse_or_outsourced_journal_operations', models.CharField(choices=[('in-house', 'Inhouse'), ('out-sourced', 'Outsourced'), ('both', 'Both')], max_length=11)),
                ('price_breakdown_journal_operations', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_publication', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_communication', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_general', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_surplus_other_revenue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_breakdown_discounts_and_waivers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
