# Generated by Django 3.2.13 on 2022-07-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='issn',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='upload',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='counter_5_unique_item_requests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='issn',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='upload',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile'),
            preserve_default=False,
        ),
    ]
