# Generated by Django 3.2.13 on 2022-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220726_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairopenaccessalliance',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationpower',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
