# Generated by Django 3.2.13 on 2022-08-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20220802_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpower',
            name='discounts_and_waivers_policy',
        ),
    ]
