# Generated by Django 3.2.13 on 2022-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_informationpower_discounts_and_waivers_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairopenaccessalliance',
            name='publisher',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='fairopenaccessalliance',
            name='publisher_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informationpower',
            name='publisher',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='informationpower',
            name='publisher_id',
            field=models.IntegerField(default=0),
        ),
    ]
