# Generated by Django 3.2.13 on 2022-10-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20220913_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='subscription_list_price_for_member_of_the_association_of_americ',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='subscription_list_price_for_member_of_the_association_of_americ',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
