# Generated by Django 3.2.13 on 2023-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20231201_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='apc_waiver_discount_policy',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='discounts_and_waivers_policy',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fairopenaccessalliance',
            name='subscription_discount_policy',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='apc_waiver_discount_policy',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='price_transparency_context',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='informationpower',
            name='subscription_discount_policy',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
