from django.urls import path
from . import views, ins_views, report_views, export_views, compare_views

urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('coalitions/users/', views.coalitions_account_search, name='coalitions_account_search'),
    path('coalitions/user_report/', report_views.user_reports, name='coalitions_user_report'),
    path('download_user_report/', report_views.download_user_reports, name="download_user_reports"),
    path('superpublisher/', views.s_publisher_dashboard, name='s_publisher_dashboard'),
    path('superpublisher/generate', views.generate_new_activation_link, name='s_publisher_generate'),
    path('superpublisher/users/', views.publisher_users, name='s_publisher_users'),
    path('superpublisher/awaitingusers/<id>/', views.publisher_awaiting_user, name='s_publisher_awaiting_user'),
    path('superpublisher/approvedusers/<id>/', views.publisher_approved_user, name='s_publisher_approved_user'),
    path('superpublisher/archived_user/<id>/', views.publisher_archived_user, name='s_publisher_archived_user'),
    path('superpublisher/pubnewlink/', views.create_publisher_link, name='publisher_new_link'),
    path('coalitions/awaitingusers/<id>/', views.publisher_awaiting_superuser, name='coalitions_awaiting_user'),
    path('coalitions/awaiting_contract_signing_users/<id>/', views.publisher_awaiting_contract_signing_superuser,
                                                                                name='coalitions_awaiting_user'),
    path('coalitions/approvedusers/<id>/', views.publisher_approved_superuser, name='coalitions_approved_user'),
    path('coalitions/archived_user/<id>/', views.publisher_archived_superuser, name='coalitions_archived_user'),
    path('coalitions/awaiting_ins_users/<id>/', ins_views.awaiting_ins_superuser, name='coalitions_awaiting_ins_user'),
    path('coalitions/awaiting_contract_signing_ins_users/<id>/', ins_views.awaiting_contract_signing_ins_superuser,
                                                                name='coalitions_awaiting_ins_user'),
    path('coalitions/approved_ins_users/<id>/', ins_views.approved_ins_superuser, name='coalitions_approved_ins_user'),
    path('coalitions/archived_ins_users/<id>/', ins_views.archived_ins_superuser, name='coalitions_archived_ins_user'),
    path('publisher/', views.publisher_dashboard, name='publisher_dashboard'),
    path('institutionalsuperuser/', ins_views.ins_s_user_dashboard, name='ins_s_user_dashboard'),
    path('institutionalsuperuser/users/', ins_views.ins_s_user_users, name='ins_s_users'),
    path('s_ins/awaitingusers/<id>/', ins_views.ins_awaiting_user, name='s_ins_awaiting_user'),
    path('s_ins/approvedusers/<id>/', ins_views.ins_approved_user, name='s_ins_approved_user'),
    path('s_ins/archived_user/<id>/', ins_views.ins_archived_user, name='s_ins_archived_user'),
    path('s_ins/generate', ins_views.generate_new_activation_link, name='s_publisher_generate'),
    path('s_ins/insnewlink/', ins_views.create_ins_link, name='ins_new_link'),
    path('institutionaluser/', ins_views.ins_user_dashboard, name='ins_user_dashboard'),
    path('journal/<str:journal_id>', ins_views.journal, name="journal"),
    path('journal/<str:journal_id>/<int:year>', ins_views.journal, name="journal_by_year"),
    path('download/<id>/', export_views.download_file, name="export_download"),
    path('comparedata/<issns>/', compare_views.compare_data, name="compare_data"),
    path('publishers', ins_views.publishers, name="publishers"),
    # Uncomment the journals urls when publisher journal search is enabled
    # path("publishers/journals/", views.publisher_journal_search, name="publisher_journal_search"),
    # path('publisher/journal/<str:journal_id>', views.journal, name="my_journal"),
    # path('publisher/journal/<str:journal_id>/<int:year>', views.journal, name="my_journal_by_year"),
    path('export/', export_views.export, name="export"),
    path('set_tnc_cookie/', ins_views.set_tnc_cookie, name="set_tnc_cookie"),
    path('download_file/<int:file_id>', views.download_file, name='download_file')
]
