"""
Django settings for pstf project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import logging.handlers
from pathlib import Path
import os
import sys
import dotenv
import datetime
from django.contrib.messages import constants as message_constants

# load environment variables from env file
dotenv.load_dotenv()

VERSION = 1.0

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DOMAIN_NAME = os.environ.get('DOMAIN_NAME', 'http://localhost:8000')

# Application definition
sys.modules['fontawesome_free'] = __import__('fontawesome-free')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'django_agent_trust',
    'session_security',
    'fontawesome_free',
    'material',
    'material.frontend',
    'viewflow',
    'viewflow.frontend',
    'accounts',
    'data',
    'login',
    'registration',
    'dashboard',
    'upload',
    'docs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    'django_agent_trust.middleware.AgentMiddleware',
    # 'csp.middleware.CSPMiddleware',
    'pstf.middleware.UserSessionMiddleware',
    'pstf.middleware.PreviousPageHandler'
]

ROOT_URLCONF = 'pstf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django_agent_trust.context_processors.agent'
            ],
        },
    },
]

WSGI_APPLICATION = 'pstf.wsgi.application'

# Custom messages levels

SPREADSHEET = 35

MESSAGE_TAGS = {message_constants.DEBUG: 'debug',
                message_constants.INFO: 'info',
                message_constants.SUCCESS: 'success',
                message_constants.WARNING: 'warning',
                SPREADSHEET: 'spreadsheet',
                message_constants.ERROR: 'error',
                }

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_NAME'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ['POSTGRES_HOST'],
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Django-storages S3 file storage backend
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Local project folder where static files will be collected
STATIC_ROOT = 'staticfiles'

# Local project folder where uploaded files will be saved
# MEDIA_ROOT = 'files'

# Default login url, redirected to if login_required decorator used
LOGIN_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.PSTFUser'

AUTHENTICATION_BACKENDS = ['accounts.backends.PSTFBackend']

# Setting cache to be file cache as it needs to be persistent for rate-limiting
# there is an issue with using Postgres db as cache for rate-limit
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}

# This logging configuration uses the socket handler to allow for
# multiple processes logging concurrently
# dev.py overwrites logging conf with
LOGGING = {
    'version': 1,  # the dictConfig format version
    'disable_existing_loggers': False,  # retain the default loggers
    'handlers': {
        'default': {
            'class': 'logging.handlers.SocketHandler',
            'host': 'localhost',
            'port': logging.handlers.DEFAULT_TCP_LOGGING_PORT,  # 9020
            'formatter': 'verbose',
        },
        'django': {
            'class': 'logging.handlers.SocketHandler',
            'host': 'localhost',
            'port': 9021
        },
        'audit': {
            'class': 'logging.handlers.SocketHandler',
            'host': 'localhost',
            'port': 9022
        }
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['default'],
        },
        'django': {
            'level': 'INFO',
            'handlers': ['django'],
        },
        'data.audit_log': {
            'level': 'INFO',
            'handlers': ['audit'],
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} {module} {lineno} || {message}',
            'style': '{',
        },
    },
}

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': os.environ.get('ELASTICSEARCH_HOST', 'elasticsearch:9200')
    },
}

ELASTICSEARCH_INDEX_SETTINGS = {
    "number_of_shards": 2,
    "number_of_replicas": 0
}

ELASTICSEARCH_INDICES = ['pstf_index_1', 'pstf_index_2']
ELASTICSEARCH_ALIAS = 'pstf_journals'

ES_AUTOCOMPLETE_JOURNAL_INDICES = ['pstf_journal_ac_1', "pstf_journal_ac_2"]
ES_AUTOCOMPLETE_JOURNAL_ALIAS = 'pstf_journal_ac'

ES_AUTOCOMPLETE_PUBLISHER_INDICES = ['pstf_publisher_ac_1', "pstf_publisher_ac_2"]
ES_AUTOCOMPLETE_PUBLISHER_ALIAS = 'pstf_publisher_ac'

ES_AUTOCOMPLETE_DISCIPLINE_INDICES = ['pstf_discipline_ac_1', "pstf_discipline_ac_2"]
ES_AUTOCOMPLETE_DISCIPLINE_ALIAS = 'pstf_discipline_ac'

ES_RESET_PREFIXES = ['pstf_index_*', "pstf_journal_ac_*", "pstf_publisher_ac_*", "pstf_discipline_ac_*"]

# Deployment setting
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-y^gsm6mc@2q81d%pdikc0h9k#c5z9+c8r76)85ky_)a1bxdq6t')

# Content Security Policy
# see https://django-csp.readthedocs.io/en/latest/configuration.html
# current policy allows only to fetch from own domain and fonts from Google
CSP_IMG_SRC = ("'self'")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", 'https://fonts.googleapis.com')
CSP_SCRIPT_SRC = ("'self'", "'sha256-k6/uegT/YGAQvbdzS6Ak1o4NHjWP3KE+OgOeh6EMuQg='",
                  "'sha256-kpJFPOMcc4zREZNkO5Ze8t1oUXaFvvAxNx6oNgqWfEM='",
                  "'sha256-zNWK6rvXyT0MNh2ZNFeYaRIo41RGXNTYVQKs/q9i5VM='",
                  "'sha256-oJ9dYzxzMYsjH/PXbf/vKyM9ZCme+UmcnmoWIUu+2AM='",
                  "'sha256-QaMgL6Jjk4CypIkQbWyV97v3hjfFTDYFWe8dAVbhhbE='",
                  "'sha256-zFrDl8JGNBGb+TIMHhtuWSOweUZueenZ+x+txeqleKk='")
CSP_FONT_SRC = ("'self'", 'https://fonts.gstatic.com/')


# Custom app settings
OTP_VALID = 600
OTP_VALID_MINUTES = str(int(OTP_VALID / 60))
DAY_LIMIT_FOR_2FA = 28
# set the number of days the Publisher User link is valid
P_USER_LINK_VALID_IN_DAYS = 30
# number of days to keep export data dump files (zip files inn temp dir)
DATA_DUMP_FILES_MAX_AGE = os.environ.get('DATA_DUMP_FILES_MAX_AGE', 7) #days

# Session settings
TEMPLATE_CONTEXT_PROCESSORS = 'django.core.context_processors.request'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SECURITY_WARN_AFTER = 870
SESSION_SECURITY_EXPIRE_AFTER = 900

# Rate limit
RATE_LIMIT = '10/30m'
RATE_LIMIT_SECONDS = 1800

# Email settings
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
EMAIL_USE_TLS = True
SENDER_ADDRESS = os.environ.get('SENDER_ADDRESS', 'no-reply@jcs.cottagelabs.com')
FEEDBACK_EMAIL = "jcs@cottagelabs.zendesk.com"
BCC_NOTIFICATION_EMAIL = os.environ.get('BCC_NOTIFICATION_EMAIL', 'jcs@cottagelabs.com')

# If set to true, emails will be sent to ADMIN_EMAIL defined in constants if either of the
# scheduled jobs, build_index or scheduled_data_dump raises an exception
REPORT_SCHEDULED_JOB_FAILURES = False

# Name of the issuer of the TOTP to be saved via QR code
ISSUER_NAME = os.environ.get('ISSUER_NAME', 'Journal Comparison Service')

# Twilio settings for SMS
TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
TWILIO_PHONENUMBER = os.environ['TWILIO_PHONENUMBER']
TWILIO_SENDER_ID = os.environ.get('TWILIO_SENDER_ID', 'JCS')

# AWS settings
AWS_S3_FILE_OVERWRITE = os.environ.get('AWS_S3_FILE_OVERWRITE', True)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', None)
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', None)
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', None)
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', None)

# Create Github issues
TRACK_ON_GITHUB = os.environ.get('TRACK_ON_GITHUB', False)
GITHUB_ISSUES_API = os.environ.get('GITHUB_ISSUES_API', None)
GITHUB_CARDS_API = os.environ.get('GITHUB_CARDS_API', None)
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', None)

# T&C Popup Consent settings
TNC_COOKIE_KEY = "jcs_tnc_cookie"   # note this is hard-coded into the base.html template, so if you change it here, change it there too unfortunately
TNC_COOKIE_VALUE = """By using this Service, you acknowledge that your access to the Service is subject to complying with the applicable competition law rules. In particular, you agree that you will not, directly or indirectly, share with or make available the information provided by the Service to non-authorized persons, and in particular to publishers"""
TNC_COOKIE_MAX_AGE = 30 * 24 * 60 * 60  # about a month

# Disable FOAA TODO: Remove all FOAA code. Issue#650
FOAA_DISABLE_DATE = datetime.date(2024, 10, 31)
