# Generated by Django 3.2.8 on 2022-05-10 01:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import pyotp
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccountRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=30)),
                ('account_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TradeBodiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
                ('esf_name', models.CharField(max_length=100)),
                ('esf_email', models.EmailField(max_length=254)),
                ('postal_address1', models.CharField(max_length=100)),
                ('postal_address2', models.CharField(blank=True, max_length=100)),
                ('postal_address3', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=300)),
                ('journal', models.CharField(max_length=200)),
                ('issn', models.CharField(max_length=50)),
                ('services_other', models.CharField(blank=True, max_length=100)),
                ('inasp_journals', models.CharField(blank=True, choices=[('AJO', 'African Journals Online'), ('BJO', 'Bangladesh Journals Online'), ('CAMJOL', 'Central American Journals Online'), ('MJOL', 'Mongolia Journals Online'), ('NJOL', 'Nepal Journals Online'), ('PJOL', 'Philippines Journals Online'), ('SJOL', 'Sri Lanka Journals Online'), ('VJOL', 'Vietnam Journals Online')], max_length=100)),
                ('member_of_cope', models.BooleanField(default=False)),
                ('member_of_publisher_trade_body', models.BooleanField(default=False)),
                ('trade_bodies_other', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(to='accounts.ServicesModel')),
                ('trade_bodies', models.ManyToManyField(to='accounts.TradeBodiesModel')),
            ],
        ),
        migrations.CreateModel(
            name='PSTFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(max_length=8, null=True)),
                ('otp_generated', models.DateTimeField(null=True)),
                ('sms_otp', models.CharField(max_length=8, null=True)),
                ('sms_otp_generated', models.DateTimeField(null=True)),
                ('hotp_counter', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(null=True)),
                ('mfa_hash', models.CharField(blank=True, default=pyotp.random_base32, max_length=50)),
                ('state', models.CharField(choices=[('LO', 'User is logged out.'), ('EOS', "OTP has been sent to user's email address."), ('EOC', 'OTP emailed to user has been confirmed.'), ('TP', 'TOTP is pending.'), ('SOS', "OTP has been sent to user's mobile phone."), ('LI', 'User is logged in.')], default='LO', max_length=3)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.publisheraccount')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
