# Generated by Django 3.2.13 on 2022-07-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('postal_address1', models.CharField(max_length=100)),
                ('postal_address2', models.CharField(blank=True, max_length=100)),
                ('postal_address3', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('ror_id', models.CharField(blank=True, max_length=150)),
                ('home_page_url', models.URLField(max_length=300)),
                ('esf_name', models.CharField(max_length=100)),
                ('esf_email', models.EmailField(max_length=254)),
                ('open_access_agreement', models.CharField(max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pstfuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='accounts.enduseraccount'),
        ),
    ]
