# Generated by Django 3.2.13 on 2022-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220726_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pstfuser',
            name='rate_exceeded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pstfuser',
            name='review_status',
            field=models.CharField(choices=[('ar', 'awaiting_review'), ('acs', 'awaiting_contract_signing'), ('app', 'approved'), ('rej', 'rejected')], default='ar', max_length=6),
        ),
    ]
