# Generated by Django 3.2.13 on 2023-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220908_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduseraccount',
            name='organisation_type',
            field=models.CharField(choices=[('INS_UNI', 'Institution/University'), ('LIBRARY', 'Library consortium'), ('FUNDER', 'cOAlition S funder')], default='INS_UNI', max_length=50),
        ),
        migrations.AddField(
            model_name='pstfuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
