from upload.frameworks import Framework, ISSNValidation, DisciplineValidation, DecimalValidation, CurrencyValidation, \
    IntValidation, PercentageValidation, FrequencyValidation, OperationsValidation, URLValidation, StrValidation

frameworks = {
    'ip': Framework(name='Information Power',
                    fields=[{'name': 'ISSN',
                             'validation': ISSNValidation},
                            {'name': 'Journal Title',
                             'validation': StrValidation},
                            {'name': 'Cluster',
                             'validation': StrValidation,
                             'required': False},
                            {'name': 'Discipline',
                             'validation': DisciplineValidation},
                            {'name': 'Owner ROR ID',
                             'validation': StrValidation,
                             'required': False},
                            {'name': 'Publisher ROR ID',
                             'validation': StrValidation,
                             'required': False},
                            {'name': 'APC List Price Range Lower',
                             'validation': DecimalValidation},
                            {'name': 'APC List Price Range Higher',
                             'validation': DecimalValidation,
                             'greater_than': 'APC List Price Range Lower'},
                            {'name': 'APC List Price Currency',
                             'validation': CurrencyValidation},
                            {'name': 'APC Waiver Discount Policy',
                             'validation': URLValidation,
                             'required': False},
                            {'name': 'Subscription List Price Range Lower',
                             'validation': DecimalValidation},
                            {'name': 'Subscription List Price Range Higher',
                             'validation': DecimalValidation,
                             'greater_than': 'Subscription List Price Range Lower'},
                            {'name': 'Subscription List Price For Member of The Association of American Universities (in USD)',
                             'validation': DecimalValidation},
                            {'name': 'Subscription List Price Currency',
                             'validation': CurrencyValidation},
                            {'name': 'Subscription Discount Policy',
                             'validation': URLValidation,
                             'required': False},
                            {'name': 'Price Transparency Context',
                             'validation': URLValidation,
                             'required': False},
                            {'name': 'Research Articles Published',
                             'validation': IntValidation},
                            {'name': 'Acceptance Rate',
                             'validation': PercentageValidation},
                            {'name': 'Desk Rejection Rate',
                             'validation': PercentageValidation},
                            {'name': 'Issue Publication Frequency',
                             'validation': FrequencyValidation},
                            {'name': 'Median Number Reviews',
                             'validation': DecimalValidation},
                            {'name': 'Median Time Submission To First Decision',
                             'validation': DecimalValidation},
                            {'name': 'Median Time Peer Review',
                             'validation': DecimalValidation},
                            {'name': 'Median Time Acceptance To Publication',
                             'validation': DecimalValidation},
                            {'name': 'Counter 5 Unique Item Requests',
                             'required': False,
                             'validation': DecimalValidation},
                            {'name': 'Counter 5 Total Item Requests',
                             'validation': DecimalValidation},
                            {'name': 'Price Breakdown: Journal Community Development',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Journal Submission On First Decision',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Peer Review',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Services Acceptance Publication',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Services Post Publication',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Platform Development Support',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Sales Marketing',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Price Breakdown: Author Customer Support',
                             'validation': PercentageValidation,
                             'summed': True},
                            {'name': 'Notes',
                             'validation': StrValidation,
                             'required': False}
                            ],
                    ),
    'foaa': Framework(name='Fair Open Access Alliance',
                      fields=[{'name': 'ISSN',
                               'validation': ISSNValidation},
                              {'name': 'Journal Title',
                               'validation': StrValidation},
                              {'name': 'Cluster',
                               'validation': StrValidation,
                               'required': False},
                              {'name': 'Discipline',
                               'validation': DisciplineValidation},
                              {'name': 'Owner ROR ID',
                               'validation': StrValidation,
                               'required': False},
                              {'name': 'Publisher ROR ID',
                               'validation': StrValidation,
                               'required': False},
                              {'name': 'APC List Price Range Lower',
                               'validation': DecimalValidation},
                              {'name': 'APC List Price Range Higher',
                               'validation': DecimalValidation,
                               'greater_than': 'APC List Price Range Lower'},
                              {'name': 'APC List Price Currency',
                               'validation': CurrencyValidation},
                              {'name': 'APC Waiver Discount Policy',
                               'validation': URLValidation,
                               'required': False},
                              {'name': 'Subscription List Price Range Lower',
                               'validation': DecimalValidation},
                              {'name': 'Subscription List Price Range Higher',
                               'validation': DecimalValidation,
                               'greater_than': 'Subscription List Price Range Lower'},
                              {'name': 'Subscription List Price For Member of The Association of American Universities (in USD)',
                               'validation': DecimalValidation},
                              {'name': 'Subscription List Price Currency',
                               'validation': CurrencyValidation},
                              {'name': 'Subscription Discount Policy',
                               'validation': URLValidation,
                               'required': False},
                              {'name': 'In-house or Outsourced Journal Operations?',
                               'validation': OperationsValidation},
                              {'name': 'Rejection Rate',
                               'validation': PercentageValidation},
                              {'name': 'Discounts and Waivers Policy',
                               'validation': URLValidation,
                               'required': False},
                              {'name': 'Price Breakdown: Journal Operations',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: Publication',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: Fees',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: Communication',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: General',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: Surplus / Other Revenue',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Price Breakdown: Discounts & Waivers',
                               'validation': PercentageValidation,
                               'summed': True},
                              {'name': 'Notes',
                               'validation': StrValidation,
                               'required': False}
                              ],
                      ),

}
