# Generated by Django 3.2.13 on 2023-01-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_insselfregisterprocess_insuserlinkregisterprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='insselfregisterprocess',
            name='otp_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='insselfregisterprocess',
            name='valid_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuserlinkregisterprocess',
            name='otp_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='insuserlinkregisterprocess',
            name='valid_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherlinkregisterprocess',
            name='otp_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='publisherlinkregisterprocess',
            name='valid_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherselfregisterprocess',
            name='otp_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='publisherselfregisterprocess',
            name='valid_otp',
            field=models.BooleanField(default=False),
        ),
    ]
