# Generated by Django 3.2.8 on 2022-05-10 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=upload.models.publisher_directory)),
                ('framework', models.CharField(choices=[('ip', 'Information Power'), ('foaa', 'Fair Open Access Alliance')], max_length=4)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('data_year', models.IntegerField(default=upload.models.last_year)),
                ('journals', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ISSNs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=4)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisheraccount')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
        ),
    ]
