# Generated by Django 3.2.13 on 2023-11-20 13:40

from django.db import migrations, models
import django.db.models.deletion

from upload.models import UploadFile


def populate_publisher_and_username(apps, schema_editor):
    for upload_file in UploadFile.objects.all():
        if upload_file.user:
            upload_file.publisher = upload_file.user.publisher
            upload_file.user_name = upload_file.user.name
            upload_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231020_1329'),
        ('upload', '0002_delete_issns'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.publisheraccount'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RunPython(populate_publisher_and_username),
    ]
