# Generated by Django 3.2.13 on 2023-12-13 09:37

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20231120_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(max_length=500, upload_to=upload.models.publisher_directory),
        ),
    ]
